### ISSUE TITLE
enableShutdownHooks error

### ISSUE THREAD

**Issue by hkjeffchan** [DevAngsy/nestjs-redis#335]
"@liaoliaots/nestjs-redis": "^9.0.1",
nestjs 9.0.8

if app.enableShutdownHooks() is called, the following error will be thrown

[Nest] 32992  - 10/08/2022, 02:40:50   ERROR [NestApplicationContext] Error happened during shutdown
Error: Nest could not find Symbol() element (this provider does not exist in the current context)
    at InstanceLinksHost.get (/xxx/node_modules/@nestjs/core/injector/instance-links-host.js:21:19)
    at ModuleRef.find (/xxx/node_modules/@nestjs/core/injector/module-ref.js:39:55)
    at ModuleRef.get (/xxx/node_modules/@nestjs/core/injector/module.js:351:28)
    at RedisModule.onApplicationShutdown (/xxx/node_modules/@liaoliaots/nestjs-redis/dist/redis/redis.module.js:68:48)
    at callAppShutdownHook (/xxx/node_modules/@nestjs/core/hooks/on-app-shutdown.hook.js:51:35)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at NestApplication.callShutdownHook (/xxx/node_modules/@nestjs/core/nest-application-context.js:208:13)
    at process.cleanup (/xxx/node_modules/@nestjs/core/nest-application-context.js:146:17)

**Comment by quyennt21** [comment]
Same issues

**Comment by quyennt21** [comment]
Maybe fix error:
- Start Microservices after start http
- remove enableShutdownHooks

**Comment by tngan** [comment]
@hkjeffchan Have you resolved this issue?

**Comment by hkjeffchan** [comment]
> @hkjeffchan Have you resolved this issue?

no, I just disabled that

**Comment by nick4fake** [comment]
Any news? This literally makes the method useless

**Comment by nick4fake** [comment]
And shouldn't be onApplicationShutdown replaced with onModuleDestroy?

**Comment by nick4fake** [comment]
This change introduces it:
https://github.com/liaoliaots/nestjs-redis/pull/320

**Comment by DecathectZero** [comment]
I have a fix here: https://github.com/liaoliaots/nestjs-redis/pull/536

**Comment by mamun-prospect** [comment]
any new version for that change?
